"""Configuration tabs for simulation pipeline stages."""
from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QScrollArea, QGroupBox, QFormLayout,
    QLabel, QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox, QCheckBox, QPushButton
)

from pathlib import Path

from sim2blender.core.paths import PROJECT_ROOT


class ConfigTabsMixin:
    """Mixin providing pipeline stage configuration tabs for MainWindow."""
    def _update_wave_model(self, *_):
        irregular = self.env_wave_type.currentData() == 'jonswap'
        self.env_height_label.setText('Significant height Hs:' if irregular else 'Height H:')
        self.env_period_label.setText('Peak period Tp:' if irregular else 'Period T:')
        self.env_wave_length.setEnabled(not irregular)
        self.env_wave_length.setToolTip('JONSWAP wavelengths follow deep-water dispersion for each period.')
        for widget in (self.env_jonswap_gamma, self.env_wave_components,
                       self.env_wave_seed, self.env_wave_spread_deg):
            widget.setEnabled(irregular)

    def _apply_env_preset(self, index: int):
        if index == 0:  # Calm Sea (Default)
            self.env_wave_height.setValue(0.30)
            self.env_wave_period.setValue(6.0)
            self.env_wave_length.setValue(25.0)
            self.env_current_speed.setValue(0.15)
        elif index == 1:  # Moderate Swell
            self.env_wave_height.setValue(1.20)
            self.env_wave_period.setValue(5.0)
            self.env_wave_length.setValue(35.0)
            self.env_current_speed.setValue(0.50)
        elif index == 2:  # Rough Sea
            self.env_wave_height.setValue(2.50)
            self.env_wave_period.setValue(4.0)
            self.env_wave_length.setValue(50.0)
            self.env_current_speed.setValue(1.20)
        elif index == 3:  # Flat Surface
            self.env_wave_height.setValue(0.00)
            self.env_wave_period.setValue(5.0)
            self.env_wave_length.setValue(30.0)
            self.env_current_speed.setValue(0.00)

    # -------------------------------------------------------------
    # Configuration Tabs Construction
    # -------------------------------------------------------------
    def _build_tab_environment(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        content = QWidget()
        v = QVBoxLayout(content)
        scroll.setWidget(content)
        layout.addWidget(scroll)

        gb_water = QGroupBox('Ocean Water Surface & Depth')
        fw = QFormLayout(gb_water)
        self.env_water_level = QDoubleSpinBox()
        self.env_water_level.setRange(-50.0, 50.0)
        self.env_water_level.setDecimals(2)
        self.env_water_level.setValue(0.0)
        self.env_water_level.setSuffix(' m')
        fw.addRow('Water Level Z', self.env_water_level)

        self.env_water_depth = QDoubleSpinBox()
        self.env_water_depth.setRange(1.0, 1000.0)
        self.env_water_depth.setValue(100.0)
        self.env_water_depth.setSuffix(' m')
        fw.addRow('Water Body Depth', self.env_water_depth)

        self.env_water_size = QDoubleSpinBox()
        self.env_water_size.setRange(10.0, 5000.0)
        self.env_water_size.setValue(300.0)
        self.env_water_size.setSuffix(' m')
        fw.addRow('Surface Extent', self.env_water_size)

        self.env_enable_volume = QCheckBox('Enable underwater volume light absorption')
        self.env_enable_volume.setChecked(True)
        fw.addRow('Underwater Volume', self.env_enable_volume)
        v.addWidget(gb_water)

        gb_presets = QGroupBox('Sea State Presets')
        fp = QFormLayout(gb_presets)
        self.env_preset_combo = QComboBox()
        self.env_preset_combo.addItems(['Calm Sea (Default)', 'Moderate Swell', 'Rough Sea', 'Flat Surface'])
        self.env_preset_combo.currentIndexChanged.connect(self._apply_env_preset)
        fp.addRow('Sea State Preset', self.env_preset_combo)
        v.addWidget(gb_presets)

        gb_waves = QGroupBox('Ocean Wave Parameters')
        fwave = QFormLayout(gb_waves)

        w_row1 = QHBoxLayout()
        self.env_wave_height = QDoubleSpinBox()
        self.env_wave_height.setRange(0.0, 15.0)
        self.env_wave_height.setDecimals(2)
        self.env_wave_height.setValue(0.30)
        self.env_wave_height.setSuffix(' m')

        self.env_wave_period = QDoubleSpinBox()
        self.env_wave_period.setRange(0.1, 60.0)
        self.env_wave_period.setDecimals(2)
        self.env_wave_period.setValue(6.0)
        self.env_wave_period.setSuffix(' s')
        self.env_height_label = QLabel('Height H:')
        w_row1.addWidget(self.env_height_label)
        w_row1.addWidget(self.env_wave_height)
        self.env_period_label = QLabel('Period T:')
        w_row1.addWidget(self.env_period_label)
        w_row1.addWidget(self.env_wave_period)
        fwave.addRow('Wave Dimensions', w_row1)

        w_row2 = QHBoxLayout()
        self.env_wave_length = QDoubleSpinBox()
        self.env_wave_length.setRange(0.5, 500.0)
        self.env_wave_length.setDecimals(1)
        self.env_wave_length.setValue(25.0)
        self.env_wave_length.setSuffix(' m')

        self.env_wave_dir = QDoubleSpinBox()
        self.env_wave_dir.setRange(-360.0, 360.0)
        self.env_wave_dir.setDecimals(1)
        self.env_wave_dir.setValue(0.0)
        self.env_wave_dir.setSuffix(' °')
        w_row2.addWidget(QLabel('Wavelength λ:'))
        w_row2.addWidget(self.env_wave_length)
        w_row2.addWidget(QLabel('Direction:'))
        w_row2.addWidget(self.env_wave_dir)
        fwave.addRow('Wave Propagation', w_row2)
        self.env_wave_type = QComboBox()
        self.env_wave_type.addItem('Regular', 'regular')
        self.env_wave_type.addItem('JONSWAP irregular', 'jonswap')
        fwave.insertRow(0, 'Wave Model', self.env_wave_type)
        self.env_jonswap_gamma = QDoubleSpinBox()
        self.env_jonswap_gamma.setRange(1, 10)
        self.env_jonswap_gamma.setValue(3.3)
        fwave.addRow('Peak enhancement gamma', self.env_jonswap_gamma)
        self.env_wave_components = QSpinBox()
        self.env_wave_components.setRange(8, 256)
        self.env_wave_components.setValue(64)
        fwave.addRow('Spectrum components', self.env_wave_components)
        self.env_wave_seed = QSpinBox()
        self.env_wave_seed.setRange(0, 2147483647)
        self.env_wave_seed.setValue(42)
        fwave.addRow('Random seed', self.env_wave_seed)
        self.env_wave_spread_deg = QDoubleSpinBox()
        self.env_wave_spread_deg.setRange(0, 90)
        self.env_wave_spread_deg.setValue(20)
        fwave.addRow('Heading spread (degrees, std. dev.)', self.env_wave_spread_deg)
        self.env_wave_type.currentIndexChanged.connect(self._update_wave_model)
        self._update_wave_model()
        v.addWidget(gb_waves)

        gb_current = QGroupBox('Water Current Vector')
        fcurr = QFormLayout(gb_current)
        c_row = QHBoxLayout()
        self.env_current_speed = QDoubleSpinBox()
        self.env_current_speed.setRange(0.0, 10.0)
        self.env_current_speed.setDecimals(2)
        self.env_current_speed.setValue(0.15)
        self.env_current_speed.setSuffix(' m/s')

        self.env_current_dir = QDoubleSpinBox()
        self.env_current_dir.setRange(-360.0, 360.0)
        self.env_current_dir.setDecimals(1)
        self.env_current_dir.setValue(0.0)
        self.env_current_dir.setSuffix(' °')
        c_row.addWidget(QLabel('Current Speed U:'))
        c_row.addWidget(self.env_current_speed)
        c_row.addWidget(QLabel('Flow Direction:'))
        c_row.addWidget(self.env_current_dir)
        fcurr.addRow('Mean Current Flow', c_row)
        v.addWidget(gb_current)

        v.addStretch()
        self.tab_config.addTab(tab, '🌊 Environment')

    # Configuration Tabs Construction
    # -------------------------------------------------------------
    def _build_tab_replay(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        content = QWidget()
        v = QVBoxLayout(content)
        scroll.setWidget(content)
        layout.addWidget(scroll)

        gb_source = QGroupBox('AquaSim Results File & Wave Timing')
        f = QFormLayout(gb_source)
        self.results = QLineEdit()
        self.results.setPlaceholderText('Matching AquaSim text export (e.g. out.txt)')
        self.results.textChanged.connect(self.results_changed)
        f.addRow('Results File', self.path_row(self.results, self.browse_results))

        r_timing = QHBoxLayout()
        self.wave_period = QDoubleSpinBox()
        self.wave_period.setDecimals(4)
        self.wave_period.setRange(0.0001, 86400)
        self.wave_period.setValue(5.0)
        self.wave_period.setSuffix(' s')
        self.wave_period.valueChanged.connect(self.update_duration)
        self.frames_per_wave = QSpinBox()
        self.frames_per_wave.setRange(1, 1000000)
        self.frames_per_wave.setValue(40)
        self.frames_per_wave.valueChanged.connect(self.update_duration)
        self.fps = QSpinBox()
        self.fps.setRange(1, 240)
        self.fps.setValue(25)
        self.fps.valueChanged.connect(self.update_duration)
        r_timing.addWidget(QLabel('Wave Period:'))
        r_timing.addWidget(self.wave_period)
        r_timing.addWidget(QLabel('Frames/Wave:'))
        r_timing.addWidget(self.frames_per_wave)
        r_timing.addWidget(QLabel('Video FPS:'))
        r_timing.addWidget(self.fps)
        f.addRow('Wave Setup', r_timing)

        self.timing_summary = QLabel('Select a results file to calculate total time.')
        self.timing_summary.setWordWrap(True)
        f.addRow(self.timing_summary)
        v.addWidget(gb_source)

        gb_timeline = QGroupBox('Timeline & Scope Control')
        ft = QFormLayout(gb_timeline)
        self.replay_start_offset = QSpinBox()
        self.replay_start_offset.setRange(0, 100000)
        self.replay_start_offset.setValue(0)
        self.replay_max_samples = QSpinBox()
        self.replay_max_samples.setRange(0, 1000000)
        self.replay_max_samples.setValue(0)
        self.replay_max_samples.setToolTip('0 = all available samples')
        ft.addRow('Start Sample Offset', self.replay_start_offset)
        ft.addRow('Max Samples (0=all)', self.replay_max_samples)
        self.replay_loop = QCheckBox('Loop animation cycle')
        self.replay_loop.setChecked(False)
        ft.addRow('Cyclic Motion', self.replay_loop)
        v.addWidget(gb_timeline)

        v.addStretch()
        self.tab_config.addTab(tab, '🌊 Replay')

    def _build_tab_schooling(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        content = QWidget()
        v = QVBoxLayout(content)
        scroll.setWidget(content)
        layout.addWidget(scroll)

        gb_pop = QGroupBox('Fish Population & Biological Dimensions')
        f = QFormLayout(gb_pop)
        self.fish_count = QSpinBox()
        self.fish_count.setRange(0, 100000)
        self.fish_count.setValue(1000)
        self.fish_count.setGroupSeparatorShown(True)
        f.addRow('Number of Fish', self.fish_count)

        self.fish_species = QLineEdit('Atlantic salmon')
        f.addRow('Species Name', self.fish_species)

        geom_row = QHBoxLayout()
        self.fish_length_mean = QDoubleSpinBox()
        self.fish_length_mean.setRange(0.05, 5.0)
        self.fish_length_mean.setDecimals(3)
        self.fish_length_mean.setValue(0.775)
        self.fish_length_mean.setSuffix(' m')
        self.fish_length_std = QDoubleSpinBox()
        self.fish_length_std.setRange(0.001, 1.0)
        self.fish_length_std.setDecimals(3)
        self.fish_length_std.setValue(0.05)
        self.fish_length_std.setSuffix(' m')
        geom_row.addWidget(QLabel('Mean Length μ:'))
        geom_row.addWidget(self.fish_length_mean)
        geom_row.addWidget(QLabel('Std Dev σ:'))
        geom_row.addWidget(self.fish_length_std)
        f.addRow('Body Length N(μ, σ²)', geom_row)

        self.fish_nominal_weight = QDoubleSpinBox()
        self.fish_nominal_weight.setRange(0.01, 50.0)
        self.fish_nominal_weight.setValue(5.0)
        self.fish_nominal_weight.setSuffix(' kg')
        f.addRow('Nominal Weight', self.fish_nominal_weight)
        v.addWidget(gb_pop)

        gb_boids = QGroupBox('Reynolds Boids Social Dynamics')
        fb = QFormLayout(gb_boids)
        sep_row = QHBoxLayout()
        self.fish_separation_weight = QDoubleSpinBox()
        self.fish_separation_weight.setRange(0.0, 5.0)
        self.fish_separation_weight.setValue(0.35)
        self.fish_separation_radius = QDoubleSpinBox()
        self.fish_separation_radius.setRange(0.1, 10.0)
        self.fish_separation_radius.setValue(1.2)
        self.fish_separation_radius.setSuffix(' m')
        sep_row.addWidget(QLabel('Weight:'))
        sep_row.addWidget(self.fish_separation_weight)
        sep_row.addWidget(QLabel('Radius:'))
        sep_row.addWidget(self.fish_separation_radius)
        fb.addRow('Collision Separation', sep_row)

        align_row = QHBoxLayout()
        self.fish_alignment_weight = QDoubleSpinBox()
        self.fish_alignment_weight.setRange(0.0, 5.0)
        self.fish_alignment_weight.setValue(0.25)
        self.fish_neighbor_radius = QDoubleSpinBox()
        self.fish_neighbor_radius.setRange(0.5, 20.0)
        self.fish_neighbor_radius.setValue(2.5)
        self.fish_neighbor_radius.setSuffix(' m')
        align_row.addWidget(QLabel('Weight:'))
        align_row.addWidget(self.fish_alignment_weight)
        align_row.addWidget(QLabel('Radius:'))
        align_row.addWidget(self.fish_neighbor_radius)
        fb.addRow('Velocity Alignment', align_row)

        self.fish_school_cohesion = QDoubleSpinBox()
        self.fish_school_cohesion.setRange(0.0, 5.0)
        self.fish_school_cohesion.setValue(0.15)
        fb.addRow('Local School Cohesion', self.fish_school_cohesion)
        v.addWidget(gb_boids)

        gb_milling = QGroupBox('Aquaculture Milling Orbit & Depth Band')
        fm = QFormLayout(gb_milling)
        self.fish_flow_direction = QComboBox()
        self.fish_flow_direction.addItems(['Counter-Clockwise (+Z)', 'Clockwise (-Z)'])
        fm.addRow('Rotational Orbit Direction', self.fish_flow_direction)

        mill_row = QHBoxLayout()
        self.fish_milling_weight = QDoubleSpinBox()
        self.fish_milling_weight.setRange(0.0, 5.0)
        self.fish_milling_weight.setValue(0.45)
        self.fish_cohesion = QDoubleSpinBox()
        self.fish_cohesion.setRange(0.0, 1.0)
        self.fish_cohesion.setValue(0.08)
        mill_row.addWidget(QLabel('Milling Drive:'))
        mill_row.addWidget(self.fish_milling_weight)
        mill_row.addWidget(QLabel('Cage Center Centripetal:'))
        mill_row.addWidget(self.fish_cohesion)
        fm.addRow('Orbit Dynamics', mill_row)

        depth_row = QHBoxLayout()
        self.fish_depth_min = QDoubleSpinBox()
        self.fish_depth_min.setRange(-100.0, 0.0)
        self.fish_depth_min.setValue(-12.0)
        self.fish_depth_min.setSuffix(' m')
        self.fish_depth_max = QDoubleSpinBox()
        self.fish_depth_max.setRange(-100.0, 0.0)
        self.fish_depth_max.setValue(-2.5)
        self.fish_depth_max.setSuffix(' m')
        depth_row.addWidget(QLabel('Bottom Z:'))
        depth_row.addWidget(self.fish_depth_min)
        depth_row.addWidget(QLabel('Top Z:'))
        depth_row.addWidget(self.fish_depth_max)
        fm.addRow('Preferred Depth Band', depth_row)

        vert_row = QHBoxLayout()
        self.fish_depth_weight = QDoubleSpinBox()
        self.fish_depth_weight.setRange(0.0, 5.0)
        self.fish_depth_weight.setValue(0.25)
        self.fish_vert_osc = QDoubleSpinBox()
        self.fish_vert_osc.setRange(0.0, 5.0)
        self.fish_vert_osc.setValue(0.35)
        self.fish_vert_osc.setSuffix(' m')
        vert_row.addWidget(QLabel('Depth Restoring:'))
        vert_row.addWidget(self.fish_depth_weight)
        vert_row.addWidget(QLabel('Oscillation Amp:'))
        vert_row.addWidget(self.fish_vert_osc)
        fm.addRow('Vertical Restoring & Wave', vert_row)
        v.addWidget(gb_milling)

        gb_kinematics = QGroupBox('Boundary Avoidance & Kinematics')
        fk = QFormLayout(gb_kinematics)
        self.fish_cruise_speed = QDoubleSpinBox()
        self.fish_cruise_speed.setRange(0.01, 10.0)
        self.fish_cruise_speed.setDecimals(2)
        self.fish_cruise_speed.setValue(0.85)
        self.fish_cruise_speed.setSuffix(' BL/s')
        fk.addRow('Cruise Speed', self.fish_cruise_speed)

        wall_row = QHBoxLayout()
        self.fish_wall_detection = QDoubleSpinBox()
        self.fish_wall_detection.setRange(0.1, 10.0)
        self.fish_wall_detection.setValue(1.5)
        self.fish_wall_detection.setSuffix(' m')
        self.fish_wall_avoidance = QDoubleSpinBox()
        self.fish_wall_avoidance.setRange(0.0, 10.0)
        self.fish_wall_avoidance.setValue(0.75)
        wall_row.addWidget(QLabel('Sensing Distance:'))
        wall_row.addWidget(self.fish_wall_detection)
        wall_row.addWidget(QLabel('Steering Force:'))
        wall_row.addWidget(self.fish_wall_avoidance)
        fk.addRow('Predictive Wall Avoidance', wall_row)

        turn_row = QHBoxLayout()
        self.fish_wall_buffer = QDoubleSpinBox()
        self.fish_wall_buffer.setRange(0.0, 5.0)
        self.fish_wall_buffer.setValue(0.05)
        self.fish_wall_buffer.setSuffix(' m')
        self.fish_max_turn_rate = QDoubleSpinBox()
        self.fish_max_turn_rate.setRange(10.0, 360.0)
        self.fish_max_turn_rate.setValue(120.0)
        self.fish_max_turn_rate.setSuffix(' °/s')
        turn_row.addWidget(QLabel('Wall Clearance:'))
        turn_row.addWidget(self.fish_wall_buffer)
        turn_row.addWidget(QLabel('Max Turn Rate:'))
        turn_row.addWidget(self.fish_max_turn_rate)
        fk.addRow('Wall Margin & Turning Limit', turn_row)

        self.fish_seed = QSpinBox()
        self.fish_seed.setRange(0, 2147483647)
        self.fish_seed.setValue(7)
        fk.addRow('Random Seed', self.fish_seed)
        v.addWidget(gb_kinematics)

        gb_tail = QGroupBox('Swimming Undulation & Tail Motion')
        ft = QFormLayout(gb_tail)
        self.fish_tail_motion = QCheckBox('Enable Procedural Tail Undulation')
        self.fish_tail_motion.setChecked(True)
        ft.addRow(self.fish_tail_motion)

        tail_row = QHBoxLayout()
        self.fish_tail_amplitude = QDoubleSpinBox()
        self.fish_tail_amplitude.setRange(0.0, 0.5)
        self.fish_tail_amplitude.setDecimals(3)
        self.fish_tail_amplitude.setSingleStep(0.005)
        self.fish_tail_amplitude.setValue(0.065)
        self.fish_tail_amplitude.setSuffix(' m')

        self.fish_tail_frequency = QDoubleSpinBox()
        self.fish_tail_frequency.setRange(0.1, 10.0)
        self.fish_tail_frequency.setDecimals(2)
        self.fish_tail_frequency.setSingleStep(0.1)
        self.fish_tail_frequency.setValue(2.2)
        self.fish_tail_frequency.setSuffix(' Hz')

        tail_row.addWidget(QLabel('Amplitude:'))
        tail_row.addWidget(self.fish_tail_amplitude)
        tail_row.addWidget(QLabel('Frequency:'))
        tail_row.addWidget(self.fish_tail_frequency)
        ft.addRow('Tail Motion Dynamics', tail_row)
        v.addWidget(gb_tail)

        v.addStretch()
        self.tab_config.addTab(tab, '🐟 Schooling')

    def _build_tab_feed(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        content = QWidget()
        v = QVBoxLayout(content)
        scroll.setWidget(content)
        layout.addWidget(scroll)

        gb_models = QGroupBox('3D Spreader Models (OBJ)')
        fm = QFormLayout(gb_models)
        self.spreader_preset_combo = QComboBox()
        self._populate_spreader_presets()
        self.spreader_preset_combo.currentIndexChanged.connect(self._on_spreader_preset_changed)
        fm.addRow('Model Preset', self.spreader_preset_combo)

        default_move = str(PROJECT_ROOT / 'assets/spreaders/default/spreader_move.obj')
        default_still = str(PROJECT_ROOT / 'assets/spreaders/default/spreader_still.obj')
        self.spreader_move_edit = QLineEdit(default_move)
        fm.addRow('Rotating Rotor OBJ', self.path_row(self.spreader_move_edit, self.browse_spreader_move))
        self.spreader_still_edit = QLineEdit(default_still)
        fm.addRow('Stationary Base OBJ', self.path_row(self.spreader_still_edit, self.browse_spreader_still))

        row_waterline = QHBoxLayout()
        self.spreader_z_offset = QDoubleSpinBox()
        self.spreader_z_offset.setRange(-10.0, 10.0)
        self.spreader_z_offset.setDecimals(3)
        self.spreader_z_offset.setSingleStep(0.05)
        self.spreader_z_offset.setValue(0.52)
        self.spreader_z_offset.setSuffix(' m')
        self.spreader_z_offset.setToolTip('Vertical lift of the spreader model above the water line (0.52m for default model)')
        row_waterline.addWidget(self.spreader_z_offset)

        self.btn_visualize_waterline = QPushButton('Visualize in Blender 🌊')
        self.btn_visualize_waterline.setToolTip('Open Blender to visualize and set the water line for this spreader model')
        self.btn_visualize_waterline.clicked.connect(self.visualize_spreader_waterline)
        row_waterline.addWidget(self.btn_visualize_waterline)
        fm.addRow('Water Line Lift (Z)', row_waterline)

        self.spreader_heave_rao = QDoubleSpinBox()
        self.spreader_heave_rao.setRange(0.0, 2.0)
        self.spreader_heave_rao.setDecimals(2)
        self.spreader_heave_rao.setSingleStep(0.05)
        self.spreader_heave_rao.setValue(0.50)
        self.spreader_heave_rao.setToolTip('Heave Response Amplitude Operator (RAO) for wave-induced spreader vertical motion (default: 0.50)')
        fm.addRow('Heave RAO', self.spreader_heave_rao)

        v.addWidget(gb_models)

        gb_rotor = QGroupBox('Rotor Kinematics & Discharge Flow')
        fr = QFormLayout(gb_rotor)
        r_flow = QHBoxLayout()
        self.feed_rpm = QDoubleSpinBox()
        self.feed_rpm.setRange(-300.0, 300.0)
        self.feed_rpm.setValue(-30.0)
        self.feed_rpm.setSuffix(' RPM')
        self.feed_mass_flow = QDoubleSpinBox()
        self.feed_mass_flow.setRange(0.1, 1000.0)
        self.feed_mass_flow.setValue(30.0)
        self.feed_mass_flow.setSuffix(' kg/min')
        r_flow.addWidget(QLabel('Rotor:'))
        r_flow.addWidget(self.feed_rpm)
        r_flow.addWidget(QLabel('Mass Flow:'))
        r_flow.addWidget(self.feed_mass_flow)
        fr.addRow('Discharge', r_flow)

        r_proxy = QHBoxLayout()
        self.feed_pellet_mass = QDoubleSpinBox()
        self.feed_pellet_mass.setDecimals(4)
        self.feed_pellet_mass.setRange(0.0001, 1.0)
        self.feed_pellet_mass.setValue(0.01)
        self.feed_pellet_mass.setSuffix(' kg')
        self.feed_lifetime = QDoubleSpinBox()
        self.feed_lifetime.setRange(1.0, 600.0)
        self.feed_lifetime.setValue(30.0)
        self.feed_lifetime.setSuffix(' s')
        r_proxy.addWidget(QLabel('Visual Mass:'))
        r_proxy.addWidget(self.feed_pellet_mass)
        r_proxy.addWidget(QLabel('Lifetime:'))
        r_proxy.addWidget(self.feed_lifetime)
        fr.addRow('Particle Proxy', r_proxy)
        v.addWidget(gb_rotor)

        gb_pellet = QGroupBox('Pellet Geometry & Morphology')
        fp = QFormLayout(gb_pellet)
        geom_row = QHBoxLayout()
        self.pellet_radius_mean = QDoubleSpinBox()
        self.pellet_radius_mean.setDecimals(4)
        self.pellet_radius_mean.setRange(0.0005, 0.1)
        self.pellet_radius_mean.setValue(0.005)
        self.pellet_radius_mean.setSuffix(' m')
        self.pellet_radius_std = QDoubleSpinBox()
        self.pellet_radius_std.setDecimals(5)
        self.pellet_radius_std.setRange(0.00001, 0.05)
        self.pellet_radius_std.setValue(0.0008)
        self.pellet_radius_std.setSuffix(' m')
        self.pellet_aspect_ratio = QDoubleSpinBox()
        self.pellet_aspect_ratio.setDecimals(2)
        self.pellet_aspect_ratio.setRange(0.5, 10.0)
        self.pellet_aspect_ratio.setValue(1.6)
        geom_row.addWidget(QLabel('Mean Radius:'))
        geom_row.addWidget(self.pellet_radius_mean)
        geom_row.addWidget(QLabel('Std Dev:'))
        geom_row.addWidget(self.pellet_radius_std)
        geom_row.addWidget(QLabel('Aspect L/D:'))
        geom_row.addWidget(self.pellet_aspect_ratio)
        fp.addRow('Dimensions', geom_row)
        v.addWidget(gb_pellet)

        gb_fluid = QGroupBox('Dual-Medium Fluid & Ballistic Physics')
        ff = QFormLayout(gb_fluid)
        eject_row = QHBoxLayout()
        self.feed_outward_speed = QDoubleSpinBox()
        self.feed_outward_speed.setDecimals(2)
        self.feed_outward_speed.setRange(0.0, 50.0)
        self.feed_outward_speed.setValue(1.0)
        self.feed_outward_speed.setSuffix(' m/s')
        self.feed_downward_speed = QDoubleSpinBox()
        self.feed_downward_speed.setDecimals(4)
        self.feed_downward_speed.setRange(0.0, 50.0)
        self.feed_downward_speed.setValue(0.001)
        self.feed_downward_speed.setSuffix(' m/s')
        eject_row.addWidget(QLabel('Radial Outward:'))
        eject_row.addWidget(self.feed_outward_speed)
        eject_row.addWidget(QLabel('Downward Vertical:'))
        eject_row.addWidget(self.feed_downward_speed)
        ff.addRow('Ejection Speed', eject_row)

        dens_row = QHBoxLayout()
        self.feed_pellet_density = QDoubleSpinBox()
        self.feed_pellet_density.setRange(500.0, 3000.0)
        self.feed_pellet_density.setValue(1100.0)
        self.feed_pellet_density.setSuffix(' kg/m³')
        self.feed_water_level = QDoubleSpinBox()
        self.feed_water_level.setRange(-50.0, 50.0)
        self.feed_water_level.setValue(0.0)
        self.feed_water_level.setSuffix(' m')
        dens_row.addWidget(QLabel('Pellet Density:'))
        dens_row.addWidget(self.feed_pellet_density)
        dens_row.addWidget(QLabel('Water Level Z:'))
        dens_row.addWidget(self.feed_water_level)
        ff.addRow('Density & Water Level', dens_row)

        drag_row = QHBoxLayout()
        self.feed_water_drag = QDoubleSpinBox()
        self.feed_water_drag.setRange(0.01, 5.0)
        self.feed_water_drag.setValue(0.85)
        self.feed_air_drag = QDoubleSpinBox()
        self.feed_air_drag.setRange(0.01, 5.0)
        self.feed_air_drag.setValue(0.47)
        drag_row.addWidget(QLabel('Water Cd:'))
        drag_row.addWidget(self.feed_water_drag)
        drag_row.addWidget(QLabel('Air Cd:'))
        drag_row.addWidget(self.feed_air_drag)
        ff.addRow('Drag Coefficients', drag_row)

        self.feed_seed = QSpinBox()
        self.feed_seed.setRange(0, 2147483647)
        self.feed_seed.setValue(30030)
        ff.addRow('Random Seed', self.feed_seed)
        v.addWidget(gb_fluid)

        v.addStretch()
        self.tab_config.addTab(tab, '🌀 Feed')

    def _build_tab_feeding(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        content = QWidget()
        v = QVBoxLayout(content)
        scroll.setWidget(content)
        layout.addWidget(scroll)

        gb_sensing = QGroupBox('Sensory Detection & Ingestion Radii')
        fs = QFormLayout(gb_sensing)
        radii_row = QHBoxLayout()
        self.feeding_sensing_radius = QDoubleSpinBox()
        self.feeding_sensing_radius.setRange(0.1, 50.0)
        self.feeding_sensing_radius.setValue(2.5)
        self.feeding_sensing_radius.setSuffix(' m')
        self.feeding_ingestion_radius = QDoubleSpinBox()
        self.feeding_ingestion_radius.setRange(0.01, 5.0)
        self.feeding_ingestion_radius.setValue(0.22)
        self.feeding_ingestion_radius.setSuffix(' m')
        radii_row.addWidget(QLabel('Sensing Radius:'))
        radii_row.addWidget(self.feeding_sensing_radius)
        radii_row.addWidget(QLabel('Ingestion Radius:'))
        radii_row.addWidget(self.feeding_ingestion_radius)
        fs.addRow('Physical Radii', radii_row)

        self.feeding_attraction_weight = QDoubleSpinBox()
        self.feeding_attraction_weight.setRange(0.0, 1.0)
        self.feeding_attraction_weight.setValue(0.55)
        fs.addRow('Attraction Steering Weight', self.feeding_attraction_weight)
        v.addWidget(gb_sensing)

        gb_burst = QGroupBox('Sprint Dynamics & Satiety Model')
        fb = QFormLayout(gb_burst)
        self.feeding_burst_speed = QDoubleSpinBox()
        self.feeding_burst_speed.setRange(0.1, 20.0)
        self.feeding_burst_speed.setValue(2.0)
        self.feeding_burst_speed.setSuffix(' BL/s')
        fb.addRow('Burst Sprint Speed', self.feeding_burst_speed)

        self.feeding_cooldown = QDoubleSpinBox()
        self.feeding_cooldown.setRange(0.1, 300.0)
        self.feeding_cooldown.setValue(10.0)
        self.feeding_cooldown.setSuffix(' s')
        fb.addRow('Satiety Refractory Cooldown', self.feeding_cooldown)
        v.addWidget(gb_burst)

        gb_depth = QGroupBox('Depth Boundaries for Feeding')
        fd = QFormLayout(gb_depth)
        depth_row = QHBoxLayout()
        self.feeding_min_depth = QDoubleSpinBox()
        self.feeding_min_depth.setRange(-200.0, 0.0)
        self.feeding_min_depth.setValue(-25.0)
        self.feeding_min_depth.setSuffix(' m')
        self.feeding_max_depth = QDoubleSpinBox()
        self.feeding_max_depth.setRange(-50.0, 5.0)
        self.feeding_max_depth.setValue(0.0)
        self.feeding_max_depth.setSuffix(' m')
        depth_row.addWidget(QLabel('Min Depth Z:'))
        depth_row.addWidget(self.feeding_min_depth)
        depth_row.addWidget(QLabel('Max Depth Z:'))
        depth_row.addWidget(self.feeding_max_depth)
        fd.addRow('Active Feeding Depth Range', depth_row)
        v.addWidget(gb_depth)

        v.addStretch()
        self.tab_config.addTab(tab, '🍴 Feeding')

    def _build_tab_camera(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        content = QWidget()
        v = QVBoxLayout(content)
        scroll.setWidget(content)
        layout.addWidget(scroll)

        gb_optics = QGroupBox('Camera Optics & Depth of Field')
        fo = QFormLayout(gb_optics)
        lens_row = QHBoxLayout()
        self.camera_focal_length = QDoubleSpinBox()
        self.camera_focal_length.setRange(10.0, 300.0)
        self.camera_focal_length.setValue(32.0)
        self.camera_focal_length.setSuffix(' mm')
        self.camera_enable_dof = QCheckBox('Depth of Field')
        self.camera_enable_dof.setChecked(True)
        self.camera_fstop = QDoubleSpinBox()
        self.camera_fstop.setRange(0.5, 32.0)
        self.camera_fstop.setValue(3.5)
        self.camera_fstop.setPrefix('f/')
        lens_row.addWidget(QLabel('Focal Length:'))
        lens_row.addWidget(self.camera_focal_length)
        lens_row.addWidget(self.camera_enable_dof)
        lens_row.addWidget(self.camera_fstop)
        fo.addRow('Lens & Aperture', lens_row)

        clip_row = QHBoxLayout()
        self.camera_clip_start = QDoubleSpinBox()
        self.camera_clip_start.setRange(0.01, 10.0)
        self.camera_clip_start.setValue(0.1)
        self.camera_clip_start.setSuffix(' m')
        self.camera_clip_end = QDoubleSpinBox()
        self.camera_clip_end.setRange(10.0, 5000.0)
        self.camera_clip_end.setValue(500.0)
        self.camera_clip_end.setSuffix(' m')
        clip_row.addWidget(QLabel('Clip Start:'))
        clip_row.addWidget(self.camera_clip_start)
        clip_row.addWidget(QLabel('Clip End:'))
        clip_row.addWidget(self.camera_clip_end)
        fo.addRow('Clipping Planes', clip_row)
        v.addWidget(gb_optics)

        gb_waypoints = QGroupBox('Multi-Phase Trajectory Waypoints')
        fw = QFormLayout(gb_waypoints)
        aerial_row = QHBoxLayout()
        self.camera_overview_height = QDoubleSpinBox()
        self.camera_overview_height.setRange(1.0, 500.0)
        self.camera_overview_height.setValue(52.0)
        self.camera_overview_height.setSuffix(' m')
        self.camera_overview_distance = QDoubleSpinBox()
        self.camera_overview_distance.setRange(1.0, 1000.0)
        self.camera_overview_distance.setValue(104.0)
        self.camera_overview_distance.setSuffix(' m')
        aerial_row.addWidget(QLabel('Overview Height Z:'))
        aerial_row.addWidget(self.camera_overview_height)
        aerial_row.addWidget(QLabel('Overview Dist:'))
        aerial_row.addWidget(self.camera_overview_distance)
        fw.addRow('Phase 1 Aerial', aerial_row)

        dive_row = QHBoxLayout()
        self.camera_swoop_height = QDoubleSpinBox()
        self.camera_swoop_height.setRange(0.1, 50.0)
        self.camera_swoop_height.setValue(2.6)
        self.camera_swoop_height.setSuffix(' m')
        self.camera_water_depth = QDoubleSpinBox()
        self.camera_water_depth.setRange(-100.0, 0.0)
        self.camera_water_depth.setValue(-3.5)
        self.camera_water_depth.setSuffix(' m')
        dive_row.addWidget(QLabel('Swoop Height:'))
        dive_row.addWidget(self.camera_swoop_height)
        dive_row.addWidget(QLabel('Underwater Dive Z:'))
        dive_row.addWidget(self.camera_water_depth)
        fw.addRow('Phase 2 & 3', dive_row)
        v.addWidget(gb_waypoints)

        gb_timeline = QGroupBox('Phase Timeline Percentages')
        ft = QFormLayout(gb_timeline)
        phase_row = QHBoxLayout()
        self.camera_phase1_pct = QDoubleSpinBox()
        self.camera_phase1_pct.setRange(0.05, 0.90)
        self.camera_phase1_pct.setValue(0.35)
        self.camera_phase2_pct = QDoubleSpinBox()
        self.camera_phase2_pct.setRange(0.10, 0.95)
        self.camera_phase2_pct.setValue(0.60)
        phase_row.addWidget(QLabel('Phase 1 End:'))
        phase_row.addWidget(self.camera_phase1_pct)
        phase_row.addWidget(QLabel('Phase 2 End:'))
        phase_row.addWidget(self.camera_phase2_pct)
        ft.addRow('Timeline Distribution', phase_row)
        v.addWidget(gb_timeline)

        v.addStretch()
        self.tab_config.addTab(tab, '🎥 Camera')

    def _populate_spreader_presets(self):
        """Populate spreader preset dropdown dynamically from assets/spreaders subfolders."""
        self.spreader_preset_combo.clear()
        spreaders_dir = PROJECT_ROOT / 'assets' / 'spreaders'
        if spreaders_dir.is_dir():
            for sub in sorted(spreaders_dir.iterdir()):
                if sub.is_dir():
                    display_name = sub.name.upper() if len(sub.name) <= 3 else sub.name.capitalize()
                    self.spreader_preset_combo.addItem(f"{display_name} Spreader", str(sub))
        self.spreader_preset_combo.addItem("Custom...", "")

    def _on_spreader_preset_changed(self, index: int):
        """Update rotor/base OBJ paths when selecting a spreader preset."""
        folder = self.spreader_preset_combo.currentData()
        if not folder:
            return
        p = Path(folder)
        if not p.is_dir():
            return
        move_file = next((f for f in p.glob("*.obj") if "move" in f.name.lower()), None)
        still_file = next((f for f in p.glob("*.obj") if "still" in f.name.lower()), None)
        if move_file:
            self.spreader_move_edit.setText(str(move_file))
        if still_file:
            self.spreader_still_edit.setText(str(still_file))

        offset = 0.52 if "default" in p.name.lower() else 0.0
        cfg_file = p / "config.json"
        if cfg_file.is_file():
            try:
                import json
                with open(cfg_file, "r", encoding="utf-8") as f:
                    cfg_data = json.load(f)
                    if "z_offset" in cfg_data:
                        offset = float(cfg_data["z_offset"])
                    elif "spreader_z_offset" in cfg_data:
                        offset = float(cfg_data["spreader_z_offset"])
            except Exception:
                pass
        if hasattr(self, "spreader_z_offset"):
            self.spreader_z_offset.setValue(offset)

