"""Bake fish school swimming and feeding animation coupled with feed particles.

This script finds the 'Membrane cage' object inside the 'AModel cage' collection,
reads water-borne feed particles generated by 'blender_feed_animation.py', and
bakes a contained fish school that swarms toward feed particles and ingests them.

It automatically clears any previously generated 'Fish school' collection.

Can be run directly from Blender GUI Scripting workspace OR via Terminal command:
    blender scene.blend --python scripts/blender_fish_feeding_animation.py
"""

from __future__ import annotations

from pathlib import Path
import sys

import bpy

def _ensure_sim2blender_in_path() -> None:
    for start in [Path(__file__).resolve() if "__file__" in globals() and __file__ else Path.cwd().resolve()]:
        curr = start if start.is_dir() else start.parent
        for _ in range(6):
            src_dir = curr / "src"
            if (src_dir / "sim2blender").is_dir():
                src_str = str(src_dir)
                if src_str not in sys.path:
                    sys.path.insert(0, src_str)
                return
            if curr.parent == curr:
                break
            curr = curr.parent

_ensure_sim2blender_in_path()

from sim2blender.blender.fish.feeding import (
    run_fish_feeding_animation,
    cleanup_existing_fish_school,
    find_membrane_cage_object,
    build_enclosure_from_cage,
)

# -----------------------------------------------------------------------------
# 鱼群与摄食耦合参数配置 (Fish School & Feeding Coupling Configuration)
# -----------------------------------------------------------------------------
FISH_COUNT = 1000                  # 鱼群数量 (尾)
FISH_LENGTH_MEAN_M = 0.775         # 鱼体平均体长 (米, 均值 μ = 77.5 cm)
FISH_LENGTH_STD_M = 0.05           # 鱼群体长标准差 (米, 标准差 σ = 5.0 cm)
SWIM_SPEED_BL_S = 0.85             # 基准巡游速度 (BL/s, 0.85 体长/秒)
RANDOM_SEED = 7                    # 鱼群随机运动种子

HUNGER_FACTOR = 0.85               # 鱼群饥饿倾向度 (0.0~1.0, 影响摄食活跃度)
SENSORY_RADIUS_M = 6.0             # 鱼类觅食感知半径 (米, 感知落入水中的饲料)
SATIATION_DURATION_S = 4.0         # 吞食单颗饲料后的饱腹冷却时间 (秒)
FEEDING_BURST_SPEED_BL_S = 2.2     # 冲刺抢食时的爆发冲刺速度 (BL/s)

COHESION_WEIGHT = 0.08             # 鱼群向心聚集权重
VERTICAL_OSCILLATION_M = 0.35      # 垂直波动幅度 (m)
FLOW_DIRECTION = 1.0               # 巡游环流方向 (1.0 逆时针, -1.0 顺时针)
WALL_BUFFER_M = 0.05               # 网衣边界防穿透缓冲间距 (m)
SPECIES = "Atlantic salmon"        # 鱼类品种
INGESTION_RADIUS_M = 0.35          # 饲料被吞食判定的物理嘴部触碰半径 (m)


def main() -> None:
    config = {
        "fish_count": FISH_COUNT,
        "fish_length_mean_m": FISH_LENGTH_MEAN_M,
        "fish_length_std_m": FISH_LENGTH_STD_M,
        "swim_speed_bl_s": SWIM_SPEED_BL_S,
        "random_seed": RANDOM_SEED,
        "hunger_factor": HUNGER_FACTOR,
        "sensory_radius_m": SENSORY_RADIUS_M,
        "satiation_duration_s": SATIATION_DURATION_S,
        "feeding_burst_speed_bl_s": FEEDING_BURST_SPEED_BL_S,
        "cohesion_weight": COHESION_WEIGHT,
        "vertical_oscillation_m": VERTICAL_OSCILLATION_M,
        "flow_direction": FLOW_DIRECTION,
        "wall_buffer_m": WALL_BUFFER_M,
        "species": SPECIES,
        "ingestion_radius_m": INGESTION_RADIUS_M,
    }
    run_fish_feeding_animation(config)


if __name__ == "__main__":
    main()
