"""Bake fish school swimming and feeding animation coupled with feed particles.

This script finds the 'Membrane cage' object inside the 'AModel cage' collection,
reads water-borne feed particles generated by 'blender_feed_animation.py', and
bakes a contained fish school that swarms toward feed particles and ingests them.

It automatically clears any previously generated 'Fish school' collection.

Can be run directly from Blender GUI Scripting workspace OR via Terminal command:
    blender scene.blend --python scripts/blender_fish_feeding_animation.py
"""

from __future__ import annotations

import math
import os
import random
from pathlib import Path
import sys

import bmesh
import bpy
from mathutils import Vector, Quaternion

# Ensure src/ is in sys.path so sim2blender modules can be imported from any execution location
def _ensure_sim2blender_in_path() -> None:
    candidates = []
    if "__file__" in globals() and __file__:
        try:
            candidates.append(Path(__file__).resolve())
        except Exception:
            pass
    if hasattr(bpy, "data") and bpy.data.filepath:
        candidates.append(Path(bpy.data.filepath).resolve())
    candidates.append(Path.cwd().resolve())

    for start in candidates:
        curr = start if start.is_dir() else start.parent
        for _ in range(6):
            src_dir = curr / "src"
            if (src_dir / "sim2blender").is_dir():
                src_str = str(src_dir)
                if src_str not in sys.path:
                    sys.path.insert(0, src_str)
                return
            if curr.parent == curr:
                break
            curr = curr.parent

    # Hardcoded fallback for the local repository structure
    fallback_src = r"e:\GitProject\Sim2Blender\src"
    if fallback_src not in sys.path:
        sys.path.insert(0, fallback_src)

_ensure_sim2blender_in_path()

from sim2blender.blender.enclosure import Enclosure, boundary_caps, stitch_membrane_seams
from sim2blender.blender.fish.salmon import salmon_mesh




# -----------------------------------------------------------------------------
# 鱼群与摄食耦合参数配置 (Fish School & Feeding Coupling Configuration)
# -----------------------------------------------------------------------------
FISH_COUNT = 1000                  # 鱼群数量 (尾)
FISH_LENGTH_MEAN_M = 0.775        # 鱼体平均体长 (米, 均值 μ = 77.5 cm)
FISH_LENGTH_STD_M = 0.05          # 鱼群体长标准差 (米, 标准差 σ = 5.0 cm, 正态分布 N(μ, σ²))

# 鱼群游动速度定义 (单位: BL/s 体长/秒, Body Lengths per second)
SWIM_SPEED_BL_S = 0.85            # 基准巡游速度 (BL/s, 0.85 体长/秒)
FEEDING_SPEED_BL_S = 2.0          # 抢食冲刺速度 (BL/s, 2.0 体长/秒)

SENSING_RADIUS_M = 2.5            # 水下感知范围 (米, 处于该距离内的鱼会被落入水中的饲料吸引)
INGESTION_RADIUS_M = 0.22         # 摄食/吞食距离 (米, 鱼体到达该距离时判定颗粒被吞食并消失)
FEEDING_COOLDOWN_S = 10.0         # 摄食消化/饱腹冷却时间 (秒, 每条鱼在 10s 内最多只吃 1 个颗粒)
ATTRACTION_WEIGHT = 0.55          # 趋食吸引力权重 (0~1, 值越大鱼群向饲料集聚越剧烈)
WATER_LEVEL_Z = 0.0               # 水面 Z 轴高度 (m, 水下 Z <= 0)

RANDOM_SEED = 7                   # 鱼群随机运动种子


def cleanup_existing_fish_school() -> None:
    """Clear previously generated 'Fish school' collection and fish objects."""
    old_school = bpy.data.collections.get("Fish school")
    if old_school is not None:
        for old_obj in list(old_school.objects):
            bpy.data.objects.remove(old_obj, do_unlink=True)
        bpy.data.collections.remove(old_school)

    # Clean up unreferenced fish template meshes
    for mesh in list(bpy.data.meshes):
        if mesh.name.startswith("salmon") or mesh.name.startswith("Fish_"):
            if mesh.users == 0:
                bpy.data.meshes.remove(mesh)


def find_membrane_cage_object() -> bpy.types.Object:
    """Find the 'Membrane cage' object inside 'AModel cage' collection or scene."""
    # 1. Look in 'AModel cage' collection
    collection = bpy.data.collections.get("AModel cage")
    if collection is not None:
        obj = collection.objects.get("Membrane cage")
        if obj is not None:
            return obj
        for o in collection.objects:
            if o.type == "MESH" and ("membrane" in o.name.lower() or "cage" in o.name.lower()):
                return o

    # 2. Look in global scene objects
    obj = bpy.data.objects.get("Membrane cage")
    if obj is not None:
        return obj

    # 3. Fuzzy search for any mesh with 'membrane' or 'cage'
    for o in bpy.data.objects:
        if o.type == "MESH":
            name_lower = o.name.lower()
            if "membrane" in name_lower or "cage" in name_lower:
                return o

    raise RuntimeError(
        "Could not find 'Membrane cage' object in 'AModel cage' collection.\n"
        "Please ensure your Blender scene contains the net cage mesh."
    )


def build_enclosure_from_cage(cage_obj: bpy.types.Object) -> Enclosure:
    """Construct a 3D BVH Enclosure from the cage mesh geometry for boundary checking."""
    mesh = cage_obj.data
    matrix = cage_obj.matrix_world
    points = [matrix @ v.co for v in mesh.vertices]
    faces = [tuple(p.vertices) for p in mesh.polygons]

    faces_stitched = stitch_membrane_seams(faces, points)
    try:
        caps = boundary_caps(faces_stitched, points, allow_caps=True)
    except Exception:
        caps = []

    return Enclosure(points, faces_stitched + caps)


def get_feed_particle_objects() -> list[bpy.types.Object]:
    """Retrieve all animated feed pellet objects in the scene."""
    collection = bpy.data.collections.get("FishFeed_Proxy_Particles")
    if collection is None:
        return []
    return [obj for obj in collection.objects if obj.type == "MESH"]


def main() -> None:
    if bpy.context.mode != "OBJECT" and bpy.ops.object.mode_set.poll():
        bpy.ops.object.mode_set(mode="OBJECT")

    scene = bpy.context.scene
    fps = scene.render.fps / scene.render.fps_base
    frame_start = scene.frame_start
    frame_end = scene.frame_end
    total_frames = max(1, frame_end - frame_start + 1)

    # 1. Clean up existing fish school
    cleanup_existing_fish_school()

    # 2. Locate cage mesh & build 3D boundary enclosure
    cage_obj = find_membrane_cage_object()
    enclosure = build_enclosure_from_cage(cage_obj)

    rng = random.Random(RANDOM_SEED)

    # 3. Create 'Fish school' collection and instantiate salmon meshes
    school_collection = bpy.data.collections.new("Fish school")
    scene.collection.children.link(school_collection)

    template_mesh = salmon_mesh(FISH_LENGTH_MEAN_M)
    base_clearance = max(v.co.length for v in template_mesh.vertices) + FISH_LENGTH_MEAN_M * 1e-5

    fish_objects: list[bpy.types.Object] = []
    positions: list[Vector] = []
    velocities: list[Vector] = []
    fish_lengths: list[float] = []
    fish_cruise_speeds: list[float] = []
    fish_feeding_speeds: list[float] = []
    fish_clearances: list[float] = []
    last_eat_time: list[float] = [-999.0] * FISH_COUNT  # Satiety timestamp per fish

    for i in range(FISH_COUNT):
        # Sample individual body length from Normal Distribution N(μ, σ²)
        raw_length = rng.gauss(FISH_LENGTH_MEAN_M, FISH_LENGTH_STD_M)
        # Biological clamping within [μ - 3σ, μ + 3σ]
        min_length = max(0.1, FISH_LENGTH_MEAN_M - 3.0 * FISH_LENGTH_STD_M)
        max_length = FISH_LENGTH_MEAN_M + 3.0 * FISH_LENGTH_STD_M
        length_i = max(min_length, min(max_length, raw_length))

        fish_lengths.append(length_i)

        # Scale physical speeds proportionally to individual body length (BL/s * length_i)
        cruise_speed_i = SWIM_SPEED_BL_S * length_i
        feeding_speed_i = FEEDING_SPEED_BL_S * length_i
        clearance_i = base_clearance * (length_i / FISH_LENGTH_MEAN_M)

        fish_cruise_speeds.append(cruise_speed_i)
        fish_feeding_speeds.append(feeding_speed_i)
        fish_clearances.append(clearance_i)

        fish_obj = bpy.data.objects.new(f"Fish_{i + 1:03d}", template_mesh)
        school_collection.objects.link(fish_obj)
        fish_obj.rotation_mode = "QUATERNION"

        # Apply individual body length scale
        scale_ratio = length_i / FISH_LENGTH_MEAN_M
        fish_obj.scale = (scale_ratio, scale_ratio, scale_ratio)

        fish_obj["fish_species"] = "Atlantic salmon"
        fish_obj["fish_length_m"] = length_i
        fish_obj["fish_length_mean_m"] = FISH_LENGTH_MEAN_M
        fish_obj["fish_length_std_m"] = FISH_LENGTH_STD_M
        fish_objects.append(fish_obj)

        # Sample initial safe position inside net cage
        pos = enclosure.sample(rng, clearance_i)
        positions.append(pos)

        # Initial random horizontal direction
        angle = rng.uniform(0, math.tau)
        vel = Vector((math.cos(angle), math.sin(angle), rng.uniform(-0.1, 0.1))).normalized()
        velocities.append(vel)

    # 4. Fetch feed particles & initialize ingestion trackers
    feed_particles = get_feed_particle_objects()
    consumed_frames: dict[bpy.types.Object, float] = {}

    cage_center = (enclosure.low + enclosure.high) * 0.5

    # 5. Step frame-by-frame and compute coupled schooling & feeding motion
    for frame in range(frame_start, frame_end + 1):
        scene.frame_set(frame)
        elapsed_s = (frame - frame_start) / fps

        # Collect active feed particle positions at current frame
        active_feed_positions: list[Vector] = []
        for pellet in feed_particles:
            if pellet in consumed_frames:
                continue
            loc = pellet.location.copy()
            # Only particles in water (Z <= WATER_LEVEL_Z) can be targeted
            if loc.z <= WATER_LEVEL_Z:
                active_feed_positions.append(loc)

        for i, fish_obj in enumerate(fish_objects):
            p = positions[i]
            v = velocities[i]
            clearance_i = fish_clearances[i]

            # Check satiety refractory status (cooldown of 10s since last meal)
            is_satiated = (elapsed_s - last_eat_time[i]) < FEEDING_COOLDOWN_S

            # Standard schooling vector toward cage center and rotational flow
            radial = p - cage_center
            cruise_dir = Vector((-radial.y, radial.x, math.sin(elapsed_s * 0.9 + i) * 0.35))
            cruise_dir += (cage_center - p) * 0.08
            if cruise_dir.length < 1e-8:
                cruise_dir = Vector((1.0, 0.0, 0.0))
            cruise_dir.normalize()

            target_feed_pos: Vector | None = None
            min_dist = SENSING_RADIUS_M

            # Only hungry (non-satiated) fish will sense and ingest feed particles!
            if not is_satiated:
                for feed_pos in active_feed_positions:
                    dist = (feed_pos - p).length
                    if dist < min_dist:
                        min_dist = dist
                        target_feed_pos = feed_pos

                    # Check if fish ingests pellet (Consumption)
                    if dist <= INGESTION_RADIUS_M and feed_particles:
                        # Find matching pellet object
                        for pellet in feed_particles:
                            if (pellet.location - feed_pos).length < 1e-3 and pellet not in consumed_frames:
                                consumed_frames[pellet] = float(frame)
                                last_eat_time[i] = elapsed_s  # Update satiety timestamp
                                break


            # Blend cruise direction with feed attraction direction
            if target_feed_pos is not None:
                attraction_dir = (target_feed_pos - p).normalized()
                desired_dir = (cruise_dir * (1.0 - ATTRACTION_WEIGHT) + attraction_dir * ATTRACTION_WEIGHT).normalized()
                current_speed = fish_feeding_speeds[i]
            else:
                desired_dir = cruise_dir
                current_speed = fish_cruise_speeds[i]

            direction = (v * 0.82 + desired_dir * 0.18).normalized()
            step_length = current_speed / fps if frame > frame_start else 0.0

            # Advance fish position with clearance containment test
            target_p = p + direction * step_length
            if enclosure.contains(p, clearance_i + step_length) and enclosure.contains(target_p, clearance_i):
                p = target_p
            else:
                # Bounce/steer back toward cage center if nearing boundary
                direction = (cage_center - p).normalized()
                target_p = p + direction * (step_length * 0.5)
                if enclosure.contains(target_p, clearance_i):
                    p = target_p

            positions[i] = p
            velocities[i] = direction

            fish_obj.location = p
            fish_obj.rotation_quaternion = direction.to_track_quat("X", "Z")

            fish_obj.keyframe_insert("location", frame=frame)
            fish_obj.keyframe_insert("rotation_quaternion", frame=frame)


    # 6. Apply constant interpolation for clean integer frame rendering
    for fish_obj in fish_objects:
        if fish_obj.animation_data and fish_obj.animation_data.action:
            action = fish_obj.animation_data.action
            # Handle both Blender legacy fcurves and modern layered actions
            curves = []
            if hasattr(action, "fcurves"):
                curves = action.fcurves
            elif hasattr(action, "layers"):
                for layer in action.layers:
                    for strip in layer.strips:
                        for bag in strip.channelbags:
                            curves.extend(bag.fcurves)
            for curve in curves:
                for keypoint in curve.keyframe_points:
                    keypoint.interpolation = "CONSTANT"

    # 7. Update visibility drivers for consumed feed particles
    for pellet, eat_frame in consumed_frames.items():
        emit_time = pellet.get("emission_time_s", 0.0)
        emit_frame = frame_start + emit_time * fps
        for prop in ("hide_viewport", "hide_render"):
            try:
                driver = pellet.driver_add(prop).driver
                driver.type = "SCRIPTED"
                driver.expression = f"frame < {emit_frame:.8f} or frame > {eat_frame:.8f}"
            except Exception:
                pass

    # Save scene properties
    scene["fish_count"] = FISH_COUNT
    scene["fish_length_mean_m"] = FISH_LENGTH_MEAN_M
    scene["fish_length_std_m"] = FISH_LENGTH_STD_M
    scene["fish_consumed_pellets"] = len(consumed_frames)

    current_path = bpy.data.filepath
    folder = os.path.dirname(current_path) or os.getcwd()
    stem = os.path.splitext(os.path.basename(current_path))[0]
    if not stem.endswith("_fish_feeding"):
        stem += "_fish_feeding"
    save_path = os.path.join(folder, stem + ".blend")
    bpy.ops.wm.save_as_mainfile(filepath=save_path, check_existing=False)

    print(
        "FISH_FEEDING_ANIMATION_DONE",
        save_path,
        "FISH_COUNT", FISH_COUNT,
        "CONSUMED_PELLETS", len(consumed_frames),
    )


if __name__ == "__main__":
    main()
